# Generated by Django 5.0.4 on 2026-01-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='bannervideo',
        ),
        migrations.AddField(
            model_name='home',
            name='bannerimg3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
